CREATE TYPE "public"."activity_progress_status" AS ENUM('not_started', 'in_progress', 'completed');--> statement-breakpoint
CREATE TYPE "public"."activity_type" AS ENUM('file', 'lesson', 'page', 'quiz', 'text_media', 'url', 'wiki', 'workshop');--> statement-breakpoint
CREATE TYPE "public"."completion_type" AS ENUM('view', 'submit', 'grade', 'time');--> statement-breakpoint
CREATE TYPE "public"."course_status" AS ENUM('draft', 'published', 'archived');--> statement-breakpoint
CREATE TYPE "public"."enrollment_role" AS ENUM('student', 'teacher', 'ta');--> statement-breakpoint
CREATE TYPE "public"."enrollment_status" AS ENUM('active', 'suspended', 'completed', 'waitlisted');--> statement-breakpoint
CREATE TYPE "public"."quiz_question_type" AS ENUM('multiple_choice', 'true_false', 'short_answer', 'fill_blank', 'matching', 'ordering', 'essay');--> statement-breakpoint
CREATE TYPE "public"."url_open_mode" AS ENUM('same_tab', 'new_tab', 'modal');--> statement-breakpoint
CREATE TYPE "public"."workshop_phase" AS ENUM('setup', 'submission', 'assessment', 'grading', 'closed');--> statement-breakpoint
CREATE TABLE "pg-drizzle_activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sectionId" integer NOT NULL,
	"type" "activity_type" NOT NULL,
	"title" varchar(256) NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"visible" boolean DEFAULT true NOT NULL,
	"completion_type" "completion_type" DEFAULT 'view' NOT NULL,
	"completionGrade" integer,
	"completionTimeSecs" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_activity_progress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_activity_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activityId" integer NOT NULL,
	"userId" text NOT NULL,
	"status" "activity_progress_status" DEFAULT 'not_started' NOT NULL,
	"firstViewedAt" timestamp with time zone,
	"completedAt" timestamp with time zone,
	"timeSpentSecs" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "activity_progress_activity_user" UNIQUE("activityId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_announcement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_announcement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer NOT NULL,
	"authorId" text NOT NULL,
	"title" varchar(256) NOT NULL,
	"content" text NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"slug" varchar(128) NOT NULL,
	"parentId" integer,
	"description" text,
	"order" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "pg-drizzle_category_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_course_progress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_course_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer NOT NULL,
	"userId" text NOT NULL,
	"progressPct" integer DEFAULT 0 NOT NULL,
	"completedAt" timestamp with time zone,
	CONSTRAINT "course_progress_course_user" UNIQUE("courseId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_course_section" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_course_section_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"visible" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"slug" varchar(256) NOT NULL,
	"description" text,
	"categoryId" integer NOT NULL,
	"teacherId" text NOT NULL,
	"status" "course_status" DEFAULT 'draft' NOT NULL,
	"coverImageUrl" text,
	"accessKey" varchar(64),
	"maxEnrollments" integer,
	"startsAt" timestamp with time zone,
	"endsAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "pg-drizzle_course_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_enrollment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_enrollment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer NOT NULL,
	"userId" text NOT NULL,
	"role" "enrollment_role" DEFAULT 'student' NOT NULL,
	"status" "enrollment_status" DEFAULT 'active' NOT NULL,
	"enrolledAt" timestamp with time zone NOT NULL,
	"startDate" timestamp with time zone,
	"endDate" timestamp with time zone,
	CONSTRAINT "enrollment_course_user" UNIQUE("courseId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_file_resource" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"storageKey" text NOT NULL,
	"originalName" varchar(512) NOT NULL,
	"mimeType" varchar(128) NOT NULL,
	"sizeBytes" integer NOT NULL,
	"forceDownload" boolean DEFAULT false NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_grade_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_grade_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer NOT NULL,
	"name" varchar(128) NOT NULL,
	"weight" integer DEFAULT 100 NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_grade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_grade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activityId" integer NOT NULL,
	"userId" text NOT NULL,
	"gradeCategoryId" integer,
	"rawScore" integer,
	"maxScore" integer,
	"percentage" integer,
	"letterGrade" varchar(4),
	"feedback" text,
	"gradedAt" timestamp with time zone,
	"gradedById" text,
	CONSTRAINT "grade_activity_user" UNIQUE("activityId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_lesson_node" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"graph" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_message_thread" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_message_thread_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer,
	"subject" varchar(256) NOT NULL,
	"createdBy" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"threadId" integer NOT NULL,
	"authorId" text NOT NULL,
	"content" text NOT NULL,
	"sentAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"readAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_page" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"content" text DEFAULT '' NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_quiz_answer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_quiz_answer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"attemptId" integer NOT NULL,
	"questionId" integer NOT NULL,
	"answer" jsonb NOT NULL,
	"isCorrect" boolean,
	"pointsAwarded" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_quiz_attempt" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_quiz_attempt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quizActivityId" integer NOT NULL,
	"userId" text NOT NULL,
	"startedAt" timestamp with time zone NOT NULL,
	"submittedAt" timestamp with time zone,
	"score" integer,
	"maxScore" integer
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_quiz_question" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_quiz_question_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quizActivityId" integer NOT NULL,
	"type" "quiz_question_type" NOT NULL,
	"prompt" text NOT NULL,
	"options" jsonb,
	"correctAnswer" jsonb,
	"points" integer DEFAULT 1 NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_quiz" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"timeLimitSecs" integer,
	"maxAttempts" integer DEFAULT 1 NOT NULL,
	"shuffleQuestions" boolean DEFAULT false NOT NULL,
	"shuffleAnswers" boolean DEFAULT false NOT NULL,
	"showFeedback" boolean DEFAULT true NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_text_media_block" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"content" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_url_resource" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"label" varchar(256),
	"description" text,
	"open_mode" "url_open_mode" DEFAULT 'new_tab' NOT NULL,
	"thumbnailUrl" text
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_wiki_page" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_wiki_page_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activityId" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"slug" varchar(256) NOT NULL,
	"content" text DEFAULT '' NOT NULL,
	"authorId" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"lockedBy" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "wiki_page_activity_slug" UNIQUE("activityId","slug")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_wiki_revision" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_wiki_revision_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wikiPageId" integer NOT NULL,
	"content" text NOT NULL,
	"authorId" text NOT NULL,
	"version" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_workshop_assessment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_workshop_assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"submissionId" integer NOT NULL,
	"assessorId" text NOT NULL,
	"scores" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"feedback" text,
	"totalScore" integer,
	"submittedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_workshop_rubric" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_workshop_rubric_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workshopActivityId" integer NOT NULL,
	"criterion" varchar(256) NOT NULL,
	"description" text,
	"maxPoints" integer NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_workshop_submission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_workshop_submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workshopActivityId" integer NOT NULL,
	"userId" text NOT NULL,
	"content" text NOT NULL,
	"attachmentKey" text,
	"submittedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_workshop" (
	"activityId" integer PRIMARY KEY NOT NULL,
	"phase" "workshop_phase" DEFAULT 'setup' NOT NULL,
	"submissionDeadline" timestamp with time zone,
	"assessmentDeadline" timestamp with time zone,
	"maxSubmissions" integer DEFAULT 1 NOT NULL,
	"peerAssessmentsRequired" integer DEFAULT 3 NOT NULL,
	"teacherWeighting" integer DEFAULT 50 NOT NULL,
	"peerWeighting" integer DEFAULT 50 NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DROP INDEX "created_by_idx";--> statement-breakpoint
DROP INDEX "name_idx";--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "role" text DEFAULT 'student';--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "banned" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "ban_reason" text;--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "ban_expires" timestamp;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity" ADD CONSTRAINT "pg-drizzle_activity_sectionId_pg-drizzle_course_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."pg-drizzle_course_section"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity_progress" ADD CONSTRAINT "pg-drizzle_activity_progress_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity_progress" ADD CONSTRAINT "pg-drizzle_activity_progress_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_announcement" ADD CONSTRAINT "pg-drizzle_announcement_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_announcement" ADD CONSTRAINT "pg-drizzle_announcement_authorId_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course_progress" ADD CONSTRAINT "pg-drizzle_course_progress_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course_progress" ADD CONSTRAINT "pg-drizzle_course_progress_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course_section" ADD CONSTRAINT "pg-drizzle_course_section_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD CONSTRAINT "pg-drizzle_course_categoryId_pg-drizzle_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."pg-drizzle_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD CONSTRAINT "pg-drizzle_course_teacherId_user_id_fk" FOREIGN KEY ("teacherId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_enrollment" ADD CONSTRAINT "pg-drizzle_enrollment_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_enrollment" ADD CONSTRAINT "pg-drizzle_enrollment_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_file_resource" ADD CONSTRAINT "pg-drizzle_file_resource_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_grade_category" ADD CONSTRAINT "pg-drizzle_grade_category_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_grade" ADD CONSTRAINT "pg-drizzle_grade_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_grade" ADD CONSTRAINT "pg-drizzle_grade_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_grade" ADD CONSTRAINT "pg-drizzle_grade_gradeCategoryId_pg-drizzle_grade_category_id_fk" FOREIGN KEY ("gradeCategoryId") REFERENCES "public"."pg-drizzle_grade_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_grade" ADD CONSTRAINT "pg-drizzle_grade_gradedById_user_id_fk" FOREIGN KEY ("gradedById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_lesson_node" ADD CONSTRAINT "pg-drizzle_lesson_node_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message_thread" ADD CONSTRAINT "pg-drizzle_message_thread_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message_thread" ADD CONSTRAINT "pg-drizzle_message_thread_createdBy_user_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message" ADD CONSTRAINT "pg-drizzle_message_threadId_pg-drizzle_message_thread_id_fk" FOREIGN KEY ("threadId") REFERENCES "public"."pg-drizzle_message_thread"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message" ADD CONSTRAINT "pg-drizzle_message_authorId_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_notification" ADD CONSTRAINT "pg-drizzle_notification_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_page" ADD CONSTRAINT "pg-drizzle_page_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_answer" ADD CONSTRAINT "pg-drizzle_quiz_answer_attemptId_pg-drizzle_quiz_attempt_id_fk" FOREIGN KEY ("attemptId") REFERENCES "public"."pg-drizzle_quiz_attempt"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_answer" ADD CONSTRAINT "pg-drizzle_quiz_answer_questionId_pg-drizzle_quiz_question_id_fk" FOREIGN KEY ("questionId") REFERENCES "public"."pg-drizzle_quiz_question"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_attempt" ADD CONSTRAINT "pg-drizzle_quiz_attempt_quizActivityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("quizActivityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_attempt" ADD CONSTRAINT "pg-drizzle_quiz_attempt_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_question" ADD CONSTRAINT "pg-drizzle_quiz_question_quizActivityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("quizActivityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz" ADD CONSTRAINT "pg-drizzle_quiz_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_text_media_block" ADD CONSTRAINT "pg-drizzle_text_media_block_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_url_resource" ADD CONSTRAINT "pg-drizzle_url_resource_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_wiki_page" ADD CONSTRAINT "pg-drizzle_wiki_page_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_wiki_page" ADD CONSTRAINT "pg-drizzle_wiki_page_authorId_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_wiki_page" ADD CONSTRAINT "pg-drizzle_wiki_page_lockedBy_user_id_fk" FOREIGN KEY ("lockedBy") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_wiki_revision" ADD CONSTRAINT "pg-drizzle_wiki_revision_wikiPageId_pg-drizzle_wiki_page_id_fk" FOREIGN KEY ("wikiPageId") REFERENCES "public"."pg-drizzle_wiki_page"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_wiki_revision" ADD CONSTRAINT "pg-drizzle_wiki_revision_authorId_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_workshop_assessment" ADD CONSTRAINT "pg-drizzle_workshop_assessment_submissionId_pg-drizzle_workshop_submission_id_fk" FOREIGN KEY ("submissionId") REFERENCES "public"."pg-drizzle_workshop_submission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_workshop_assessment" ADD CONSTRAINT "pg-drizzle_workshop_assessment_assessorId_user_id_fk" FOREIGN KEY ("assessorId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_workshop_rubric" ADD CONSTRAINT "pg-drizzle_workshop_rubric_workshopActivityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("workshopActivityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_workshop_submission" ADD CONSTRAINT "pg-drizzle_workshop_submission_workshopActivityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("workshopActivityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_workshop_submission" ADD CONSTRAINT "pg-drizzle_workshop_submission_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_workshop" ADD CONSTRAINT "pg-drizzle_workshop_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activity_section_idx" ON "pg-drizzle_activity" USING btree ("sectionId");--> statement-breakpoint
CREATE INDEX "activity_type_idx" ON "pg-drizzle_activity" USING btree ("type");--> statement-breakpoint
CREATE INDEX "announcement_course_idx" ON "pg-drizzle_announcement" USING btree ("courseId");--> statement-breakpoint
CREATE INDEX "category_parent_idx" ON "pg-drizzle_category" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "category_slug_idx" ON "pg-drizzle_category" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "section_course_idx" ON "pg-drizzle_course_section" USING btree ("courseId");--> statement-breakpoint
CREATE INDEX "course_category_idx" ON "pg-drizzle_course" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "course_teacher_idx" ON "pg-drizzle_course" USING btree ("teacherId");--> statement-breakpoint
CREATE INDEX "course_status_idx" ON "pg-drizzle_course" USING btree ("status");--> statement-breakpoint
CREATE INDEX "course_slug_idx" ON "pg-drizzle_course" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "enrollment_course_status_idx" ON "pg-drizzle_enrollment" USING btree ("courseId","status");--> statement-breakpoint
CREATE INDEX "enrollment_user_status_idx" ON "pg-drizzle_enrollment" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "grade_category_course_idx" ON "pg-drizzle_grade_category" USING btree ("courseId");--> statement-breakpoint
CREATE INDEX "grade_user_activity_idx" ON "pg-drizzle_grade" USING btree ("userId","activityId");--> statement-breakpoint
CREATE INDEX "message_thread_course_idx" ON "pg-drizzle_message_thread" USING btree ("courseId");--> statement-breakpoint
CREATE INDEX "message_thread_sent_idx" ON "pg-drizzle_message" USING btree ("threadId","sentAt");--> statement-breakpoint
CREATE INDEX "notification_user_read_idx" ON "pg-drizzle_notification" USING btree ("userId","readAt");--> statement-breakpoint
CREATE INDEX "quiz_answer_attempt_idx" ON "pg-drizzle_quiz_answer" USING btree ("attemptId");--> statement-breakpoint
CREATE INDEX "quiz_attempt_activity_user_idx" ON "pg-drizzle_quiz_attempt" USING btree ("quizActivityId","userId");--> statement-breakpoint
CREATE INDEX "quiz_question_activity_idx" ON "pg-drizzle_quiz_question" USING btree ("quizActivityId");--> statement-breakpoint
CREATE INDEX "wiki_page_activity_idx" ON "pg-drizzle_wiki_page" USING btree ("activityId");--> statement-breakpoint
CREATE INDEX "wiki_revision_page_idx" ON "pg-drizzle_wiki_revision" USING btree ("wikiPageId");--> statement-breakpoint
CREATE INDEX "workshop_assessment_submission_idx" ON "pg-drizzle_workshop_assessment" USING btree ("submissionId","assessorId");--> statement-breakpoint
CREATE INDEX "workshop_rubric_activity_idx" ON "pg-drizzle_workshop_rubric" USING btree ("workshopActivityId");--> statement-breakpoint
CREATE INDEX "workshop_submission_activity_user_idx" ON "pg-drizzle_workshop_submission" USING btree ("workshopActivityId","userId");--> statement-breakpoint
CREATE INDEX "post_created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");