CREATE TYPE "public"."settings_digest_frequency" AS ENUM('off', 'daily', 'weekly');--> statement-breakpoint
CREATE TYPE "public"."settings_enrollment_mode" AS ENUM('open', 'approval');--> statement-breakpoint
CREATE TABLE "pg-drizzle_platform_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_platform_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"platformName" varchar(128) DEFAULT 'Modern E-Learning Portal' NOT NULL,
	"supportEmail" varchar(255) DEFAULT 'support@modern-elearning-portal.local' NOT NULL,
	"defaultCourseCapacity" integer DEFAULT 100 NOT NULL,
	"default_enrollment_mode" "settings_enrollment_mode" DEFAULT 'open' NOT NULL,
	"digest_frequency" "settings_digest_frequency" DEFAULT 'daily' NOT NULL,
	"sendSystemAnnouncements" boolean DEFAULT true NOT NULL,
	"maintenanceMode" boolean DEFAULT false NOT NULL,
	"maintenanceMessage" text DEFAULT 'Platform maintenance is in progress. Please check back shortly.' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "platform_settings_created_idx" ON "pg-drizzle_platform_settings" USING btree ("createdAt");