CREATE TYPE "public"."course_location_type" AS ENUM('online', 'onsite');--> statement-breakpoint
CREATE TABLE "pg-drizzle_course_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_course_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer NOT NULL,
	"dayOfWeek" integer NOT NULL,
	"startDate" date NOT NULL,
	"endDate" date,
	"startTime" time NOT NULL,
	"endTime" time NOT NULL,
	"location" text,
	"classroom" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD COLUMN "location_type" "course_location_type" DEFAULT 'online' NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD COLUMN "siteLocation" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD COLUMN "classroom" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD COLUMN "instructorBio" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course_session" ADD CONSTRAINT "pg-drizzle_course_session_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "course_session_course_idx" ON "pg-drizzle_course_session" USING btree ("courseId");