CREATE TYPE "public"."email_log_status" AS ENUM('pending', 'sent', 'failed', 'bounced');--> statement-breakpoint
CREATE TYPE "public"."user_digest_frequency" AS ENUM('off', 'daily', 'weekly');--> statement-breakpoint
CREATE TABLE "pg-drizzle_email_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_email_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text,
	"notificationId" integer,
	"emailType" varchar(64) NOT NULL,
	"recipientEmail" varchar(255) NOT NULL,
	"subject" varchar(512) NOT NULL,
	"status" "email_log_status" DEFAULT 'pending' NOT NULL,
	"providerResponse" text,
	"errorMessage" text,
	"createdAt" timestamp with time zone NOT NULL,
	"sentAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_notification_preference" (
	"userId" text PRIMARY KEY NOT NULL,
	"emailEnabled" boolean DEFAULT true NOT NULL,
	"digest_frequency" "user_digest_frequency" DEFAULT 'daily' NOT NULL,
	"lastDigestSentAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_platform_settings" ADD COLUMN "emailFromAddress" varchar(255) DEFAULT 'noreply@modern-elearning-portal.local' NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_platform_settings" ADD COLUMN "emailFromName" varchar(128) DEFAULT 'Modern E-Learning Portal' NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_email_log" ADD CONSTRAINT "pg-drizzle_email_log_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_email_log" ADD CONSTRAINT "pg-drizzle_email_log_notificationId_pg-drizzle_notification_id_fk" FOREIGN KEY ("notificationId") REFERENCES "public"."pg-drizzle_notification"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_notification_preference" ADD CONSTRAINT "pg-drizzle_notification_preference_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "email_log_user_created_idx" ON "pg-drizzle_email_log" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "email_log_status_created_idx" ON "pg-drizzle_email_log" USING btree ("status","createdAt");--> statement-breakpoint
CREATE INDEX "notification_preference_digest_idx" ON "pg-drizzle_notification_preference" USING btree ("digest_frequency","lastDigestSentAt");