CREATE TABLE "pg-drizzle_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"actorId" text,
	"action" varchar(64) NOT NULL,
	"resourceType" varchar(64),
	"resourceId" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ipAddress" varchar(64),
	"userAgent" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_audit_log" ADD CONSTRAINT "pg-drizzle_audit_log_actorId_user_id_fk" FOREIGN KEY ("actorId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_actor_created_idx" ON "pg-drizzle_audit_log" USING btree ("actorId","createdAt");--> statement-breakpoint
CREATE INDEX "audit_log_action_created_idx" ON "pg-drizzle_audit_log" USING btree ("action","createdAt");--> statement-breakpoint
CREATE INDEX "audit_log_resource_idx" ON "pg-drizzle_audit_log" USING btree ("resourceType","resourceId");