CREATE TYPE "public"."gamification_badge_criteria" AS ENUM('points_threshold', 'activity_count', 'quiz_count', 'course_count', 'streak_days');--> statement-breakpoint
CREATE TYPE "public"."gamification_event_source" AS ENUM('activity_completed', 'quiz_passed', 'course_completed', 'daily_login', 'badge_bonus');--> statement-breakpoint
CREATE TYPE "public"."leaderboard_scope" AS ENUM('global', 'course');--> statement-breakpoint
CREATE TYPE "public"."question_difficulty" AS ENUM('easy', 'medium', 'hard');--> statement-breakpoint
CREATE TYPE "public"."release_rule_type" AS ENUM('date', 'enrollment_offset', 'activity_completion', 'prerequisite_score', 'manual');--> statement-breakpoint
CREATE TABLE "pg-drizzle_activity_release_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_activity_release_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activityId" integer NOT NULL,
	"type" "release_rule_type" NOT NULL,
	"releaseAt" timestamp with time zone,
	"offsetDays" integer,
	"prerequisiteActivityId" integer,
	"minimumScore" integer,
	"manuallyReleased" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_badge_definition" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_badge_definition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text,
	"icon" varchar(64),
	"criteria_type" "gamification_badge_criteria" NOT NULL,
	"criteriaValue" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "pg-drizzle_badge_definition_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_gamification_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_gamification_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activityCompletedPoints" integer DEFAULT 10 NOT NULL,
	"quizPassedPoints" integer DEFAULT 25 NOT NULL,
	"courseCompletedPoints" integer DEFAULT 100 NOT NULL,
	"dailyLoginPoints" integer DEFAULT 5 NOT NULL,
	"levelThresholds" jsonb DEFAULT '[0,100,250,500,1000,2000]'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_leaderboard_snapshot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_leaderboard_snapshot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope" "leaderboard_scope" NOT NULL,
	"courseId" integer,
	"period" varchar(32) DEFAULT 'allTime' NOT NULL,
	"entries" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"calculatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "leaderboard_snapshot_scope_course_period" UNIQUE("scope","courseId","period")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_points_ledger" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_points_ledger_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"amount" integer NOT NULL,
	"source_type" "gamification_event_source" NOT NULL,
	"sourceId" text NOT NULL,
	"courseId" integer,
	"reason" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "points_ledger_user_source" UNIQUE("userId","source_type","sourceId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_question_bank_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_question_bank_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ownerId" text NOT NULL,
	"type" "quiz_question_type" NOT NULL,
	"prompt" text NOT NULL,
	"options" jsonb,
	"correctAnswer" jsonb,
	"allowMultiple" boolean DEFAULT false NOT NULL,
	"points" integer DEFAULT 1 NOT NULL,
	"recommendedTimeMins" integer DEFAULT 1 NOT NULL,
	"difficulty" "question_difficulty" DEFAULT 'medium' NOT NULL,
	"explanation" text,
	"usageCount" integer DEFAULT 0 NOT NULL,
	"attemptCount" integer DEFAULT 0 NOT NULL,
	"correctCount" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_question_bank_entry_tag" (
	"questionId" integer NOT NULL,
	"tagId" integer NOT NULL,
	CONSTRAINT "question_bank_entry_tag_unique" UNIQUE("questionId","tagId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_question_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_question_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ownerId" text NOT NULL,
	"name" varchar(64) NOT NULL,
	CONSTRAINT "question_tag_owner_name" UNIQUE("ownerId","name")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_section_release_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_section_release_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sectionId" integer NOT NULL,
	"type" "release_rule_type" NOT NULL,
	"releaseAt" timestamp with time zone,
	"offsetDays" integer,
	"prerequisiteActivityId" integer,
	"minimumScore" integer,
	"manuallyReleased" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user_badge" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_user_badge_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"badgeId" integer NOT NULL,
	"awardedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "user_badge_user_badge" UNIQUE("userId","badgeId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user_level" (
	"userId" text PRIMARY KEY NOT NULL,
	"totalPoints" integer DEFAULT 0 NOT NULL,
	"level" integer DEFAULT 1 NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user_streak" (
	"userId" text PRIMARY KEY NOT NULL,
	"currentStreak" integer DEFAULT 0 NOT NULL,
	"longestStreak" integer DEFAULT 0 NOT NULL,
	"lastActivityDate" date
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, ''))) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message_thread" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce(subject, ''))) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_question" ADD COLUMN "bankQuestionId" integer;--> statement-breakpoint
ALTER TABLE "pg-drizzle_wiki_page" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity_release_rule" ADD CONSTRAINT "pg-drizzle_activity_release_rule_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity_release_rule" ADD CONSTRAINT "pg-drizzle_activity_release_rule_prerequisiteActivityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("prerequisiteActivityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_leaderboard_snapshot" ADD CONSTRAINT "pg-drizzle_leaderboard_snapshot_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_points_ledger" ADD CONSTRAINT "pg-drizzle_points_ledger_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_points_ledger" ADD CONSTRAINT "pg-drizzle_points_ledger_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question_bank_entry" ADD CONSTRAINT "pg-drizzle_question_bank_entry_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question_bank_entry_tag" ADD CONSTRAINT "pg-drizzle_question_bank_entry_tag_questionId_pg-drizzle_question_bank_entry_id_fk" FOREIGN KEY ("questionId") REFERENCES "public"."pg-drizzle_question_bank_entry"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question_bank_entry_tag" ADD CONSTRAINT "pg-drizzle_question_bank_entry_tag_tagId_pg-drizzle_question_tag_id_fk" FOREIGN KEY ("tagId") REFERENCES "public"."pg-drizzle_question_tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question_tag" ADD CONSTRAINT "pg-drizzle_question_tag_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_section_release_rule" ADD CONSTRAINT "pg-drizzle_section_release_rule_sectionId_pg-drizzle_course_section_id_fk" FOREIGN KEY ("sectionId") REFERENCES "public"."pg-drizzle_course_section"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_section_release_rule" ADD CONSTRAINT "pg-drizzle_section_release_rule_prerequisiteActivityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("prerequisiteActivityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_badge" ADD CONSTRAINT "pg-drizzle_user_badge_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_badge" ADD CONSTRAINT "pg-drizzle_user_badge_badgeId_pg-drizzle_badge_definition_id_fk" FOREIGN KEY ("badgeId") REFERENCES "public"."pg-drizzle_badge_definition"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_level" ADD CONSTRAINT "pg-drizzle_user_level_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_streak" ADD CONSTRAINT "pg-drizzle_user_streak_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activity_release_rule_activity_idx" ON "pg-drizzle_activity_release_rule" USING btree ("activityId");--> statement-breakpoint
CREATE INDEX "badge_definition_key_idx" ON "pg-drizzle_badge_definition" USING btree ("key");--> statement-breakpoint
CREATE INDEX "gamification_config_created_idx" ON "pg-drizzle_gamification_config" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "leaderboard_snapshot_scope_course_idx" ON "pg-drizzle_leaderboard_snapshot" USING btree ("scope","courseId");--> statement-breakpoint
CREATE INDEX "points_ledger_user_created_idx" ON "pg-drizzle_points_ledger" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "question_bank_owner_idx" ON "pg-drizzle_question_bank_entry" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "question_bank_difficulty_idx" ON "pg-drizzle_question_bank_entry" USING btree ("difficulty");--> statement-breakpoint
CREATE INDEX "section_release_rule_section_idx" ON "pg-drizzle_section_release_rule" USING btree ("sectionId");--> statement-breakpoint
CREATE INDEX "user_badge_user_idx" ON "pg-drizzle_user_badge" USING btree ("userId");--> statement-breakpoint
ALTER TABLE "pg-drizzle_quiz_question" ADD CONSTRAINT "pg-drizzle_quiz_question_bankQuestionId_pg-drizzle_question_bank_entry_id_fk" FOREIGN KEY ("bankQuestionId") REFERENCES "public"."pg-drizzle_question_bank_entry"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activity_search_vector_idx" ON "pg-drizzle_activity" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "course_search_vector_idx" ON "pg-drizzle_course" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "message_thread_search_vector_idx" ON "pg-drizzle_message_thread" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "message_search_vector_idx" ON "pg-drizzle_message" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "wiki_page_search_vector_idx" ON "pg-drizzle_wiki_page" USING gin ("search_vector");