CREATE TABLE "pg-drizzle_badge_assertion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_badge_assertion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" varchar(64) NOT NULL,
	"userId" text NOT NULL,
	"courseId" integer NOT NULL,
	"certificateId" integer,
	"name" varchar(256) NOT NULL,
	"description" text,
	"issuedOn" timestamp with time zone NOT NULL,
	"expiresAt" timestamp with time zone,
	"revokedAt" timestamp with time zone,
	"evidenceUrl" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "badge_assertion_uid" UNIQUE("uid"),
	CONSTRAINT "badge_assertion_course_user" UNIQUE("courseId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_certificate_template" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_certificate_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"courseId" integer,
	"name" varchar(128) NOT NULL,
	"title" varchar(256) DEFAULT 'Certificate of Completion' NOT NULL,
	"issuer" varchar(256) DEFAULT 'Modern E-Learning Portal' NOT NULL,
	"signerName" varchar(256),
	"accentColor" varchar(16) DEFAULT '#1677ff' NOT NULL,
	"autoIssue" boolean DEFAULT true NOT NULL,
	"validityDays" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_certificate" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_certificate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"serial" varchar(64) NOT NULL,
	"userId" text NOT NULL,
	"courseId" integer NOT NULL,
	"templateId" integer,
	"issuedAt" timestamp with time zone NOT NULL,
	"expiresAt" timestamp with time zone,
	"revokedAt" timestamp with time zone,
	"svg" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "certificate_serial_unique" UNIQUE("serial"),
	CONSTRAINT "certificate_course_user" UNIQUE("courseId","userId")
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_badge_assertion" ADD CONSTRAINT "pg-drizzle_badge_assertion_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_badge_assertion" ADD CONSTRAINT "pg-drizzle_badge_assertion_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_badge_assertion" ADD CONSTRAINT "pg-drizzle_badge_assertion_certificateId_pg-drizzle_certificate_id_fk" FOREIGN KEY ("certificateId") REFERENCES "public"."pg-drizzle_certificate"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_certificate_template" ADD CONSTRAINT "pg-drizzle_certificate_template_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_certificate" ADD CONSTRAINT "pg-drizzle_certificate_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_certificate" ADD CONSTRAINT "pg-drizzle_certificate_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_certificate" ADD CONSTRAINT "pg-drizzle_certificate_templateId_pg-drizzle_certificate_template_id_fk" FOREIGN KEY ("templateId") REFERENCES "public"."pg-drizzle_certificate_template"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "badge_assertion_user_idx" ON "pg-drizzle_badge_assertion" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "certificate_template_course_idx" ON "pg-drizzle_certificate_template" USING btree ("courseId");--> statement-breakpoint
CREATE INDEX "certificate_user_idx" ON "pg-drizzle_certificate" USING btree ("userId");