CREATE TYPE "public"."learning_path_status" AS ENUM('draft', 'published', 'archived');--> statement-breakpoint
ALTER TYPE "public"."gamification_event_source" ADD VALUE 'skill_attained' BEFORE 'daily_login';--> statement-breakpoint
CREATE TABLE "pg-drizzle_activity_skill" (
	"activityId" integer NOT NULL,
	"skillId" integer NOT NULL,
	"weight" integer DEFAULT 100 NOT NULL,
	CONSTRAINT "activity_skill_unique" UNIQUE("activityId","skillId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_course_skill" (
	"courseId" integer NOT NULL,
	"skillId" integer NOT NULL,
	"weight" integer DEFAULT 100 NOT NULL,
	CONSTRAINT "course_skill_unique" UNIQUE("courseId","skillId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_learning_path" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_learning_path_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"status" "learning_path_status" DEFAULT 'draft' NOT NULL,
	"targetRole" varchar(128),
	"createdBy" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_path_course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_path_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pathId" integer NOT NULL,
	"courseId" integer NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"prerequisiteCourseId" integer,
	"requiredScore" integer,
	CONSTRAINT "path_course_unique" UNIQUE("pathId","courseId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_path_enrollment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_path_enrollment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pathId" integer NOT NULL,
	"userId" text NOT NULL,
	"progressPct" integer DEFAULT 0 NOT NULL,
	"startedAt" timestamp with time zone NOT NULL,
	"completedAt" timestamp with time zone,
	CONSTRAINT "path_enrollment_unique" UNIQUE("pathId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_path_skill_target" (
	"pathId" integer NOT NULL,
	"skillId" integer NOT NULL,
	"targetLevel" integer DEFAULT 100 NOT NULL,
	CONSTRAINT "path_skill_target_unique" UNIQUE("pathId","skillId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_skill_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_skill_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_skill" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_skill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoryId" integer,
	"name" varchar(128) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "skill_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user_skill" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_user_skill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"skillId" integer NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"evidenceCourseId" integer,
	"attainedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "user_skill_unique" UNIQUE("userId","skillId")
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_gamification_config" ADD COLUMN "skillAttainedPoints" integer DEFAULT 20 NOT NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity_skill" ADD CONSTRAINT "pg-drizzle_activity_skill_activityId_pg-drizzle_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."pg-drizzle_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_activity_skill" ADD CONSTRAINT "pg-drizzle_activity_skill_skillId_pg-drizzle_skill_id_fk" FOREIGN KEY ("skillId") REFERENCES "public"."pg-drizzle_skill"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course_skill" ADD CONSTRAINT "pg-drizzle_course_skill_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_course_skill" ADD CONSTRAINT "pg-drizzle_course_skill_skillId_pg-drizzle_skill_id_fk" FOREIGN KEY ("skillId") REFERENCES "public"."pg-drizzle_skill"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_learning_path" ADD CONSTRAINT "pg-drizzle_learning_path_createdBy_user_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_course" ADD CONSTRAINT "pg-drizzle_path_course_pathId_pg-drizzle_learning_path_id_fk" FOREIGN KEY ("pathId") REFERENCES "public"."pg-drizzle_learning_path"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_course" ADD CONSTRAINT "pg-drizzle_path_course_courseId_pg-drizzle_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_course" ADD CONSTRAINT "pg-drizzle_path_course_prerequisiteCourseId_pg-drizzle_course_id_fk" FOREIGN KEY ("prerequisiteCourseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_enrollment" ADD CONSTRAINT "pg-drizzle_path_enrollment_pathId_pg-drizzle_learning_path_id_fk" FOREIGN KEY ("pathId") REFERENCES "public"."pg-drizzle_learning_path"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_enrollment" ADD CONSTRAINT "pg-drizzle_path_enrollment_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_skill_target" ADD CONSTRAINT "pg-drizzle_path_skill_target_pathId_pg-drizzle_learning_path_id_fk" FOREIGN KEY ("pathId") REFERENCES "public"."pg-drizzle_learning_path"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_path_skill_target" ADD CONSTRAINT "pg-drizzle_path_skill_target_skillId_pg-drizzle_skill_id_fk" FOREIGN KEY ("skillId") REFERENCES "public"."pg-drizzle_skill"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_skill" ADD CONSTRAINT "pg-drizzle_skill_categoryId_pg-drizzle_skill_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."pg-drizzle_skill_category"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_skill" ADD CONSTRAINT "pg-drizzle_user_skill_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_skill" ADD CONSTRAINT "pg-drizzle_user_skill_skillId_pg-drizzle_skill_id_fk" FOREIGN KEY ("skillId") REFERENCES "public"."pg-drizzle_skill"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_skill" ADD CONSTRAINT "pg-drizzle_user_skill_evidenceCourseId_pg-drizzle_course_id_fk" FOREIGN KEY ("evidenceCourseId") REFERENCES "public"."pg-drizzle_course"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "learning_path_status_idx" ON "pg-drizzle_learning_path" USING btree ("status");--> statement-breakpoint
CREATE INDEX "path_course_path_idx" ON "pg-drizzle_path_course" USING btree ("pathId");--> statement-breakpoint
CREATE INDEX "path_enrollment_user_idx" ON "pg-drizzle_path_enrollment" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "skill_category_idx" ON "pg-drizzle_skill" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "user_skill_user_idx" ON "pg-drizzle_user_skill" USING btree ("userId");